name: CI/CD with Docker Compose
on:
 push:
   branches:
     - main
env:
  AWS_EC2_METADATA_DISABLED: true
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh root@${{ secrets.SSH_HOST }} "echo HELLO > hello.txt"
    - name: cleanup
      run: rm -rf ~/.ssh
